[2025-02-22T23:43:44.995-0500] {processor.py:186} INFO - Started process (PID=26752) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:43:44.996-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:43:45.000-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:44.999-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:43:45.021-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:45.017-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:45.022-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:43:45.055-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.069 seconds
[2025-02-22T23:44:52.899-0500] {processor.py:186} INFO - Started process (PID=27191) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:44:52.901-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:44:52.905-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:52.904-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:44:52.918-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:52.914-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:44:52.919-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:44:52.955-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.071 seconds
[2025-02-22T23:49:24.777-0500] {processor.py:186} INFO - Started process (PID=27798) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:49:24.779-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:49:24.783-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:24.782-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:49:24.793-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:24.788-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:24.793-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:49:24.825-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-22T23:50:26.553-0500] {processor.py:186} INFO - Started process (PID=28249) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:50:26.555-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:50:26.558-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:26.557-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:50:26.566-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:26.563-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:26.567-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:50:26.609-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.064 seconds
[2025-02-22T23:51:24.634-0500] {processor.py:186} INFO - Started process (PID=28634) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:51:24.637-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:51:24.640-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:24.639-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:51:24.651-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:24.645-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:24.652-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:51:24.685-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.059 seconds
[2025-02-22T23:52:22.974-0500] {processor.py:186} INFO - Started process (PID=29071) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:52:22.977-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:52:22.981-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:22.981-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:52:22.996-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:22.991-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:22.997-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:52:23.029-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.069 seconds
[2025-02-22T23:54:01.241-0500] {processor.py:186} INFO - Started process (PID=29772) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:54:01.244-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:54:01.247-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:01.246-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:54:01.262-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:01.257-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:01.263-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:54:01.307-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.079 seconds
[2025-02-22T23:55:04.614-0500] {processor.py:186} INFO - Started process (PID=30209) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:55:04.618-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:55:04.622-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:04.621-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:55:04.629-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:04.628-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:55:04.630-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:55:04.669-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.063 seconds
[2025-02-22T23:58:16.833-0500] {processor.py:186} INFO - Started process (PID=30722) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:58:16.835-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:58:16.838-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:16.837-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:58:16.855-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:16.845-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:16.856-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:58:16.930-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.109 seconds
[2025-02-22T23:59:21.745-0500] {processor.py:186} INFO - Started process (PID=31174) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:59:21.763-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-22T23:59:21.768-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:21.767-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:59:21.785-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:21.779-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:21.785-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-22T23:59:21.820-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.088 seconds
[2025-02-23T00:00:45.801-0500] {processor.py:186} INFO - Started process (PID=31712) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:00:45.804-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:00:45.809-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:45.808-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:00:45.826-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:45.817-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:00:45.827-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:00:45.873-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.084 seconds
[2025-02-23T00:01:46.643-0500] {processor.py:186} INFO - Started process (PID=32139) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:01:46.645-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:01:46.648-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:46.648-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:01:46.656-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:46.653-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:46.656-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:01:46.683-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.052 seconds
[2025-02-23T00:11:25.473-0500] {processor.py:186} INFO - Started process (PID=34433) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:11:25.476-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:11:25.480-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:25.479-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:11:25.488-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:25.486-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:25.488-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:11:25.522-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.061 seconds
[2025-02-23T00:12:39.815-0500] {processor.py:186} INFO - Started process (PID=34556) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:12:39.816-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:12:39.819-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:39.819-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:12:39.829-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:39.827-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:39.829-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:12:39.869-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.063 seconds
[2025-02-23T00:13:39.154-0500] {processor.py:186} INFO - Started process (PID=34627) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:13:39.161-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:13:39.165-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:39.164-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:13:39.172-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:39.170-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:39.172-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:13:39.202-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T00:14:37.994-0500] {processor.py:186} INFO - Started process (PID=34702) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:14:37.996-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:14:37.999-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:37.998-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:14:38.006-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:38.004-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:38.006-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:14:38.035-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.051 seconds
[2025-02-23T00:15:47.171-0500] {processor.py:186} INFO - Started process (PID=34798) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:15:47.178-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:15:47.180-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:47.180-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:15:47.188-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:47.185-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:47.189-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:15:47.220-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T00:16:52.398-0500] {processor.py:186} INFO - Started process (PID=34899) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:16:52.400-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:16:52.402-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:52.402-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:16:52.418-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:52.415-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:16:52.418-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:16:52.467-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.084 seconds
[2025-02-23T00:17:51.744-0500] {processor.py:186} INFO - Started process (PID=34977) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:17:51.750-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:17:51.753-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:51.753-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:17:51.760-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:51.758-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:51.761-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:17:51.793-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T00:22:05.934-0500] {processor.py:186} INFO - Started process (PID=35191) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:22:05.937-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:22:05.939-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:05.939-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:22:05.946-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:05.944-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:05.947-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:22:05.979-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.053 seconds
[2025-02-23T00:23:11.036-0500] {processor.py:186} INFO - Started process (PID=35258) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:23:11.042-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:23:11.046-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:11.046-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:23:11.053-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:11.051-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:11.054-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:23:11.085-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T00:24:14.488-0500] {processor.py:186} INFO - Started process (PID=35333) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:24:14.494-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:24:14.497-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:14.497-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:24:14.504-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:14.502-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:14.504-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:24:14.535-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.056 seconds
[2025-02-23T00:25:13.426-0500] {processor.py:186} INFO - Started process (PID=35402) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:25:13.428-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:25:13.433-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:13.432-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:25:13.443-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:13.441-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:13.444-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:25:13.483-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.068 seconds
[2025-02-23T00:26:12.763-0500] {processor.py:186} INFO - Started process (PID=35478) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:26:12.770-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T00:26:12.773-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:12.773-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:26:12.780-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:12.778-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:26:12.781-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T00:26:12.812-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T02:31:43.237-0500] {processor.py:186} INFO - Started process (PID=76006) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:31:43.239-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:31:43.242-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:43.242-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:31:43.249-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:43.247-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:43.249-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:31:43.284-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.056 seconds
[2025-02-23T02:32:43.342-0500] {processor.py:186} INFO - Started process (PID=76429) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:32:43.344-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:32:43.347-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:43.346-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:32:43.353-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:43.352-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:43.354-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:32:43.385-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.051 seconds
[2025-02-23T02:34:01.383-0500] {processor.py:186} INFO - Started process (PID=76832) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:34:01.390-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:34:01.393-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:01.393-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:34:01.401-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:01.399-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:34:01.401-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:34:01.430-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T02:35:27.840-0500] {processor.py:186} INFO - Started process (PID=77179) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:35:27.880-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:35:27.904-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:27.903-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:35:27.929-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:27.927-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:27.929-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:35:28.105-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.426 seconds
[2025-02-23T02:43:11.869-0500] {processor.py:186} INFO - Started process (PID=79048) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:43:11.870-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:43:11.873-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:11.872-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:43:11.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:11.880-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:11.884-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:43:11.916-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.055 seconds
[2025-02-23T02:44:11.896-0500] {processor.py:186} INFO - Started process (PID=79250) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:44:11.904-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:44:11.907-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:11.906-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:44:11.913-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:11.912-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:11.914-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:44:11.945-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T02:45:16.130-0500] {processor.py:186} INFO - Started process (PID=79450) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:45:16.132-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:45:16.135-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:16.134-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:45:16.144-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:16.142-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:45:16.145-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:45:16.177-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T02:46:15.284-0500] {processor.py:186} INFO - Started process (PID=79637) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:46:15.290-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:46:15.293-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:15.292-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:46:15.300-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:15.298-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:46:15.300-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:46:15.333-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T02:47:26.107-0500] {processor.py:186} INFO - Started process (PID=79881) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:47:26.109-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:47:26.112-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:26.111-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:47:26.121-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:26.117-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:47:26.122-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:47:26.159-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.063 seconds
[2025-02-23T02:48:29.279-0500] {processor.py:186} INFO - Started process (PID=80078) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:48:29.286-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:48:29.289-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:29.288-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:48:29.296-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:29.294-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:48:29.296-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:48:29.334-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.063 seconds
[2025-02-23T02:49:32.010-0500] {processor.py:186} INFO - Started process (PID=80270) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:49:32.018-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:49:32.020-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:32.020-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:49:32.028-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:32.026-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:49:32.028-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:49:32.061-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.060 seconds
[2025-02-23T02:51:06.370-0500] {processor.py:186} INFO - Started process (PID=80536) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:51:06.376-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:51:06.381-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:06.380-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:51:06.396-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:06.393-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:51:06.396-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:51:06.429-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.073 seconds
[2025-02-23T02:52:22.643-0500] {processor.py:186} INFO - Started process (PID=80786) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:52:22.650-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:52:22.654-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:22.653-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:52:22.662-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:22.659-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:52:22.662-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:52:22.695-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.061 seconds
[2025-02-23T02:53:26.164-0500] {processor.py:186} INFO - Started process (PID=80978) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:53:26.165-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:53:26.168-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:26.168-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:53:26.175-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:26.173-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:53:26.176-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:53:26.208-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.053 seconds
[2025-02-23T02:54:28.353-0500] {processor.py:186} INFO - Started process (PID=81172) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:54:28.355-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:54:28.358-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:28.358-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:54:28.366-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:28.363-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:54:28.366-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:54:28.401-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T02:55:29.523-0500] {processor.py:186} INFO - Started process (PID=81362) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:55:29.525-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:55:29.528-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:29.527-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:55:29.537-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:29.535-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:55:29.538-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:55:29.572-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.059 seconds
[2025-02-23T02:56:33.197-0500] {processor.py:186} INFO - Started process (PID=81582) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:56:33.201-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:56:33.203-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:33.203-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:56:33.211-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:33.209-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:56:33.211-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:56:33.252-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.064 seconds
[2025-02-23T02:57:35.505-0500] {processor.py:186} INFO - Started process (PID=81796) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:57:35.507-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:57:35.511-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:35.510-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:57:35.519-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:35.517-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:57:35.520-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:57:35.556-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.066 seconds
[2025-02-23T02:58:42.062-0500] {processor.py:186} INFO - Started process (PID=81997) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:58:42.069-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:58:42.072-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:42.072-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:58:42.079-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:42.077-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:58:42.079-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:58:42.111-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T02:59:42.977-0500] {processor.py:186} INFO - Started process (PID=82184) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:59:42.979-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T02:59:42.982-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:42.982-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:59:42.992-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:42.987-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:59:42.993-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T02:59:43.025-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.060 seconds
[2025-02-23T03:00:49.413-0500] {processor.py:186} INFO - Started process (PID=82384) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:00:49.415-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:00:49.418-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:49.417-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:00:49.427-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:49.424-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:00:49.428-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:00:49.461-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.059 seconds
[2025-02-23T03:01:59.146-0500] {processor.py:186} INFO - Started process (PID=82645) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:01:59.148-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:01:59.151-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:59.150-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:01:59.162-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:59.156-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:01:59.163-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:01:59.194-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.061 seconds
[2025-02-23T03:03:19.887-0500] {processor.py:186} INFO - Started process (PID=83476) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:03:19.891-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:03:19.902-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:19.900-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:03:19.915-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:19.912-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:03:19.916-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:03:19.953-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.079 seconds
[2025-02-23T03:04:29.140-0500] {processor.py:186} INFO - Started process (PID=83718) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:04:29.142-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:04:29.145-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:29.145-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:04:29.152-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:29.150-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:04:29.153-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:04:29.185-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.053 seconds
[2025-02-23T03:05:33.196-0500] {processor.py:186} INFO - Started process (PID=83913) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:05:33.198-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:05:33.201-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:33.200-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:05:33.207-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:33.206-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:05:33.208-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:05:33.239-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.052 seconds
[2025-02-23T03:06:34.919-0500] {processor.py:186} INFO - Started process (PID=84130) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:06:34.920-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:06:34.923-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:34.923-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:06:34.932-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:34.930-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:06:34.933-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:06:34.968-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:07:34.390-0500] {processor.py:186} INFO - Started process (PID=84309) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:07:34.393-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:07:34.396-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:34.395-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:07:34.403-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:34.401-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:07:34.404-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:07:34.432-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.050 seconds
[2025-02-23T03:08:38.916-0500] {processor.py:186} INFO - Started process (PID=84511) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:08:38.922-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:08:38.926-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:38.925-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:08:38.933-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:38.932-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:08:38.934-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:08:38.964-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:09:41.070-0500] {processor.py:186} INFO - Started process (PID=84727) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:09:41.075-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:09:41.080-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:41.079-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:09:41.098-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:41.095-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:09:41.099-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:09:41.155-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.127 seconds
[2025-02-23T03:10:47.972-0500] {processor.py:186} INFO - Started process (PID=84931) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:10:47.974-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:10:47.977-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:47.977-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:10:47.984-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:47.982-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:10:47.985-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:10:48.016-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.052 seconds
[2025-02-23T03:11:50.767-0500] {processor.py:186} INFO - Started process (PID=85153) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:11:50.809-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:11:50.814-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:50.813-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:11:50.837-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:50.833-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:11:50.838-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:11:50.992-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.246 seconds
[2025-02-23T03:12:53.255-0500] {processor.py:186} INFO - Started process (PID=85348) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:12:53.262-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:12:53.265-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:53.264-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:12:53.272-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:53.270-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:12:53.272-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:12:53.305-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:14:03.712-0500] {processor.py:186} INFO - Started process (PID=85563) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:14:03.715-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:14:03.718-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:03.717-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:14:03.726-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:03.724-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:14:03.727-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:14:03.763-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.065 seconds
[2025-02-23T03:15:08.074-0500] {processor.py:186} INFO - Started process (PID=85819) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:15:08.077-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:15:08.086-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:08.084-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:15:08.107-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:08.104-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:15:08.109-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:15:08.156-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.099 seconds
[2025-02-23T03:16:13.352-0500] {processor.py:186} INFO - Started process (PID=86027) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:16:13.359-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:16:13.363-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:13.362-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:16:13.375-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:13.371-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:16:13.376-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:16:13.416-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.079 seconds
[2025-02-23T03:17:11.159-0500] {processor.py:186} INFO - Started process (PID=86245) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:17:11.161-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:17:11.163-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:11.163-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:17:11.170-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:11.168-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:17:11.171-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:17:11.208-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:18:15.292-0500] {processor.py:186} INFO - Started process (PID=86444) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:18:15.294-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:18:15.297-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:15.297-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:18:15.304-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:15.302-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:18:15.305-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:18:15.337-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.053 seconds
[2025-02-23T03:19:19.655-0500] {processor.py:186} INFO - Started process (PID=86762) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:19:19.659-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:19:19.665-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:19.663-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:19:19.678-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:19.676-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:19:19.678-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:19:19.713-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.084 seconds
[2025-02-23T03:20:22.155-0500] {processor.py:186} INFO - Started process (PID=86960) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:20:22.157-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:20:22.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:22.159-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:20:22.166-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:22.165-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:20:22.167-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:20:22.197-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.051 seconds
[2025-02-23T03:21:22.588-0500] {processor.py:186} INFO - Started process (PID=87181) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:21:22.590-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:21:22.593-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:22.593-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:21:22.600-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:22.598-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:21:22.601-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:21:22.637-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:22:22.313-0500] {processor.py:186} INFO - Started process (PID=87391) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:22:22.320-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:22:22.323-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:22.323-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:22:22.330-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:22.328-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:22:22.331-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:22:22.363-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:23:28.552-0500] {processor.py:186} INFO - Started process (PID=87598) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:23:28.559-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:23:28.562-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:28.561-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:23:28.569-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:28.567-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:23:28.569-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:23:28.601-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T03:24:28.191-0500] {processor.py:186} INFO - Started process (PID=87786) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:24:28.193-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:24:28.196-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:28.195-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:24:28.202-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:28.201-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:24:28.203-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:24:28.232-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.050 seconds
[2025-02-23T03:25:36.867-0500] {processor.py:186} INFO - Started process (PID=88012) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:25:36.869-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:25:36.872-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:36.871-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:25:36.878-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:36.877-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:25:36.879-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:25:36.913-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.054 seconds
[2025-02-23T03:26:37.261-0500] {processor.py:186} INFO - Started process (PID=88233) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:26:37.263-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:26:37.266-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:37.265-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:26:37.273-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:37.270-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:26:37.274-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:26:37.307-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.054 seconds
[2025-02-23T03:27:35.838-0500] {processor.py:186} INFO - Started process (PID=88427) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:27:35.839-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:27:35.843-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:35.842-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:27:35.849-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:35.848-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:27:35.850-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:27:35.886-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.057 seconds
[2025-02-23T03:28:36.297-0500] {processor.py:186} INFO - Started process (PID=88611) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:28:36.304-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:28:36.307-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:36.306-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:28:36.313-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:36.312-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:28:36.314-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:28:36.351-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.063 seconds
[2025-02-23T03:29:37.662-0500] {processor.py:186} INFO - Started process (PID=88817) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:29:37.665-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:29:37.670-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:37.669-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:29:37.680-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:37.677-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:29:37.680-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:29:37.719-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.070 seconds
[2025-02-23T03:30:49.426-0500] {processor.py:186} INFO - Started process (PID=89097) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:30:49.433-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:30:49.437-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:49.436-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:30:49.453-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:49.449-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:30:49.454-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:30:49.495-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.079 seconds
[2025-02-23T03:31:49.685-0500] {processor.py:186} INFO - Started process (PID=89337) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:31:49.688-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:31:49.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:31:49.690-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:31:49.705-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:31:49.702-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:31:49.706-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:31:49.745-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.072 seconds
[2025-02-23T03:32:57.873-0500] {processor.py:186} INFO - Started process (PID=89568) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:32:57.879-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:32:57.882-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:57.882-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:32:57.890-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:57.888-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:32:57.891-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:32:57.922-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:34:06.857-0500] {processor.py:186} INFO - Started process (PID=89780) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:34:06.864-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:34:06.867-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:06.867-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:34:06.876-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:06.874-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:34:06.876-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:34:06.905-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.058 seconds
[2025-02-23T03:35:13.866-0500] {processor.py:186} INFO - Started process (PID=90009) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:35:13.867-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:35:13.870-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:13.870-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:35:13.877-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:13.875-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:35:13.878-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:35:13.909-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.052 seconds
[2025-02-23T03:36:17.873-0500] {processor.py:186} INFO - Started process (PID=90220) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:36:17.879-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:36:17.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:17.882-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:36:17.890-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:17.888-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:36:17.890-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:36:17.918-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.056 seconds
[2025-02-23T03:37:34.203-0500] {processor.py:186} INFO - Started process (PID=90469) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:37:34.205-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:37:34.209-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:34.208-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:37:34.222-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:34.218-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:37:34.223-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:37:34.274-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.083 seconds
[2025-02-23T03:38:40.717-0500] {processor.py:186} INFO - Started process (PID=90668) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:38:40.719-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:38:40.722-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:40.721-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:38:40.736-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:40.734-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:38:40.737-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:38:40.790-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.088 seconds
[2025-02-23T03:39:45.456-0500] {processor.py:186} INFO - Started process (PID=90879) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:39:45.463-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:39:45.466-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:45.466-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:39:45.474-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:45.471-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:39:45.475-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:39:45.501-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.056 seconds
[2025-02-23T03:40:54.795-0500] {processor.py:186} INFO - Started process (PID=91102) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:40:54.802-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2025-02-23T03:40:54.805-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:40:54.804-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:40:54.811-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:40:54.809-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 64, in <module>
    tutorial_etl_dag = example_sensor_decorator()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py", line 46, in example_sensor_decorator
    def wait_for_upstream() -> PokeReturnValue:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:40:54.811-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py
[2025-02-23T03:40:54.843-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sensor_decorator.py took 0.055 seconds
